// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device_metadata.proto

package com.geeksville.mesh;

public final class DeviceMetadataProtos {
  private DeviceMetadataProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DeviceMetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DeviceMetadata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Device firmware version string
     * </pre>
     *
     * <code>string firmware_version = 1;</code>
     * @return The firmwareVersion.
     */
    java.lang.String getFirmwareVersion();
    /**
     * <pre>
     * Device firmware version string
     * </pre>
     *
     * <code>string firmware_version = 1;</code>
     * @return The bytes for firmwareVersion.
     */
    com.google.protobuf.ByteString
        getFirmwareVersionBytes();

    /**
     * <pre>
     * Device state version
     * </pre>
     *
     * <code>uint32 device_state_version = 2;</code>
     * @return The deviceStateVersion.
     */
    int getDeviceStateVersion();

    /**
     * <pre>
     * Indicates whether the device can shutdown CPU natively or via power management chip
     * </pre>
     *
     * <code>bool canShutdown = 3;</code>
     * @return The canShutdown.
     */
    boolean getCanShutdown();

    /**
     * <pre>
     * Indicates that the device has native wifi capability
     * </pre>
     *
     * <code>bool hasWifi = 4;</code>
     * @return The hasWifi.
     */
    boolean getHasWifi();

    /**
     * <pre>
     * Indicates that the device has native bluetooth capability
     * </pre>
     *
     * <code>bool hasBluetooth = 5;</code>
     * @return The hasBluetooth.
     */
    boolean getHasBluetooth();

    /**
     * <pre>
     * Indicates that the device has an ethernet peripheral
     * </pre>
     *
     * <code>bool hasEthernet = 6;</code>
     * @return The hasEthernet.
     */
    boolean getHasEthernet();
  }
  /**
   * <pre>
   * Device metadata response 
   * </pre>
   *
   * Protobuf type {@code DeviceMetadata}
   */
  public static final class DeviceMetadata extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DeviceMetadata)
      DeviceMetadataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeviceMetadata.newBuilder() to construct.
    private DeviceMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeviceMetadata() {
      firmwareVersion_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DeviceMetadata();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.geeksville.mesh.DeviceMetadataProtos.internal_static_DeviceMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.geeksville.mesh.DeviceMetadataProtos.internal_static_DeviceMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata.class, com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata.Builder.class);
    }

    public static final int FIRMWARE_VERSION_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object firmwareVersion_ = "";
    /**
     * <pre>
     * Device firmware version string
     * </pre>
     *
     * <code>string firmware_version = 1;</code>
     * @return The firmwareVersion.
     */
    @java.lang.Override
    public java.lang.String getFirmwareVersion() {
      java.lang.Object ref = firmwareVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firmwareVersion_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Device firmware version string
     * </pre>
     *
     * <code>string firmware_version = 1;</code>
     * @return The bytes for firmwareVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirmwareVersionBytes() {
      java.lang.Object ref = firmwareVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firmwareVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICE_STATE_VERSION_FIELD_NUMBER = 2;
    private int deviceStateVersion_ = 0;
    /**
     * <pre>
     * Device state version
     * </pre>
     *
     * <code>uint32 device_state_version = 2;</code>
     * @return The deviceStateVersion.
     */
    @java.lang.Override
    public int getDeviceStateVersion() {
      return deviceStateVersion_;
    }

    public static final int CANSHUTDOWN_FIELD_NUMBER = 3;
    private boolean canShutdown_ = false;
    /**
     * <pre>
     * Indicates whether the device can shutdown CPU natively or via power management chip
     * </pre>
     *
     * <code>bool canShutdown = 3;</code>
     * @return The canShutdown.
     */
    @java.lang.Override
    public boolean getCanShutdown() {
      return canShutdown_;
    }

    public static final int HASWIFI_FIELD_NUMBER = 4;
    private boolean hasWifi_ = false;
    /**
     * <pre>
     * Indicates that the device has native wifi capability
     * </pre>
     *
     * <code>bool hasWifi = 4;</code>
     * @return The hasWifi.
     */
    @java.lang.Override
    public boolean getHasWifi() {
      return hasWifi_;
    }

    public static final int HASBLUETOOTH_FIELD_NUMBER = 5;
    private boolean hasBluetooth_ = false;
    /**
     * <pre>
     * Indicates that the device has native bluetooth capability
     * </pre>
     *
     * <code>bool hasBluetooth = 5;</code>
     * @return The hasBluetooth.
     */
    @java.lang.Override
    public boolean getHasBluetooth() {
      return hasBluetooth_;
    }

    public static final int HASETHERNET_FIELD_NUMBER = 6;
    private boolean hasEthernet_ = false;
    /**
     * <pre>
     * Indicates that the device has an ethernet peripheral
     * </pre>
     *
     * <code>bool hasEthernet = 6;</code>
     * @return The hasEthernet.
     */
    @java.lang.Override
    public boolean getHasEthernet() {
      return hasEthernet_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firmwareVersion_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, firmwareVersion_);
      }
      if (deviceStateVersion_ != 0) {
        output.writeUInt32(2, deviceStateVersion_);
      }
      if (canShutdown_ != false) {
        output.writeBool(3, canShutdown_);
      }
      if (hasWifi_ != false) {
        output.writeBool(4, hasWifi_);
      }
      if (hasBluetooth_ != false) {
        output.writeBool(5, hasBluetooth_);
      }
      if (hasEthernet_ != false) {
        output.writeBool(6, hasEthernet_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firmwareVersion_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, firmwareVersion_);
      }
      if (deviceStateVersion_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, deviceStateVersion_);
      }
      if (canShutdown_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, canShutdown_);
      }
      if (hasWifi_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, hasWifi_);
      }
      if (hasBluetooth_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, hasBluetooth_);
      }
      if (hasEthernet_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, hasEthernet_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata)) {
        return super.equals(obj);
      }
      com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata other = (com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata) obj;

      if (!getFirmwareVersion()
          .equals(other.getFirmwareVersion())) return false;
      if (getDeviceStateVersion()
          != other.getDeviceStateVersion()) return false;
      if (getCanShutdown()
          != other.getCanShutdown()) return false;
      if (getHasWifi()
          != other.getHasWifi()) return false;
      if (getHasBluetooth()
          != other.getHasBluetooth()) return false;
      if (getHasEthernet()
          != other.getHasEthernet()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIRMWARE_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getFirmwareVersion().hashCode();
      hash = (37 * hash) + DEVICE_STATE_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceStateVersion();
      hash = (37 * hash) + CANSHUTDOWN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCanShutdown());
      hash = (37 * hash) + HASWIFI_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasWifi());
      hash = (37 * hash) + HASBLUETOOTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasBluetooth());
      hash = (37 * hash) + HASETHERNET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasEthernet());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Device metadata response 
     * </pre>
     *
     * Protobuf type {@code DeviceMetadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DeviceMetadata)
        com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.geeksville.mesh.DeviceMetadataProtos.internal_static_DeviceMetadata_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.geeksville.mesh.DeviceMetadataProtos.internal_static_DeviceMetadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata.class, com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata.Builder.class);
      }

      // Construct using com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        firmwareVersion_ = "";
        deviceStateVersion_ = 0;
        canShutdown_ = false;
        hasWifi_ = false;
        hasBluetooth_ = false;
        hasEthernet_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.geeksville.mesh.DeviceMetadataProtos.internal_static_DeviceMetadata_descriptor;
      }

      @java.lang.Override
      public com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata getDefaultInstanceForType() {
        return com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata.getDefaultInstance();
      }

      @java.lang.Override
      public com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata build() {
        com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata buildPartial() {
        com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata result = new com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.firmwareVersion_ = firmwareVersion_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.deviceStateVersion_ = deviceStateVersion_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.canShutdown_ = canShutdown_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.hasWifi_ = hasWifi_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.hasBluetooth_ = hasBluetooth_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.hasEthernet_ = hasEthernet_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata) {
          return mergeFrom((com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata other) {
        if (other == com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata.getDefaultInstance()) return this;
        if (!other.getFirmwareVersion().isEmpty()) {
          firmwareVersion_ = other.firmwareVersion_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getDeviceStateVersion() != 0) {
          setDeviceStateVersion(other.getDeviceStateVersion());
        }
        if (other.getCanShutdown() != false) {
          setCanShutdown(other.getCanShutdown());
        }
        if (other.getHasWifi() != false) {
          setHasWifi(other.getHasWifi());
        }
        if (other.getHasBluetooth() != false) {
          setHasBluetooth(other.getHasBluetooth());
        }
        if (other.getHasEthernet() != false) {
          setHasEthernet(other.getHasEthernet());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                firmwareVersion_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                deviceStateVersion_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                canShutdown_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                hasWifi_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                hasBluetooth_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                hasEthernet_ = input.readBool();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object firmwareVersion_ = "";
      /**
       * <pre>
       * Device firmware version string
       * </pre>
       *
       * <code>string firmware_version = 1;</code>
       * @return The firmwareVersion.
       */
      public java.lang.String getFirmwareVersion() {
        java.lang.Object ref = firmwareVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firmwareVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Device firmware version string
       * </pre>
       *
       * <code>string firmware_version = 1;</code>
       * @return The bytes for firmwareVersion.
       */
      public com.google.protobuf.ByteString
          getFirmwareVersionBytes() {
        java.lang.Object ref = firmwareVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firmwareVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Device firmware version string
       * </pre>
       *
       * <code>string firmware_version = 1;</code>
       * @param value The firmwareVersion to set.
       * @return This builder for chaining.
       */
      public Builder setFirmwareVersion(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        firmwareVersion_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Device firmware version string
       * </pre>
       *
       * <code>string firmware_version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirmwareVersion() {
        firmwareVersion_ = getDefaultInstance().getFirmwareVersion();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Device firmware version string
       * </pre>
       *
       * <code>string firmware_version = 1;</code>
       * @param value The bytes for firmwareVersion to set.
       * @return This builder for chaining.
       */
      public Builder setFirmwareVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        firmwareVersion_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int deviceStateVersion_ ;
      /**
       * <pre>
       * Device state version
       * </pre>
       *
       * <code>uint32 device_state_version = 2;</code>
       * @return The deviceStateVersion.
       */
      @java.lang.Override
      public int getDeviceStateVersion() {
        return deviceStateVersion_;
      }
      /**
       * <pre>
       * Device state version
       * </pre>
       *
       * <code>uint32 device_state_version = 2;</code>
       * @param value The deviceStateVersion to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceStateVersion(int value) {
        
        deviceStateVersion_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Device state version
       * </pre>
       *
       * <code>uint32 device_state_version = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceStateVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceStateVersion_ = 0;
        onChanged();
        return this;
      }

      private boolean canShutdown_ ;
      /**
       * <pre>
       * Indicates whether the device can shutdown CPU natively or via power management chip
       * </pre>
       *
       * <code>bool canShutdown = 3;</code>
       * @return The canShutdown.
       */
      @java.lang.Override
      public boolean getCanShutdown() {
        return canShutdown_;
      }
      /**
       * <pre>
       * Indicates whether the device can shutdown CPU natively or via power management chip
       * </pre>
       *
       * <code>bool canShutdown = 3;</code>
       * @param value The canShutdown to set.
       * @return This builder for chaining.
       */
      public Builder setCanShutdown(boolean value) {
        
        canShutdown_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Indicates whether the device can shutdown CPU natively or via power management chip
       * </pre>
       *
       * <code>bool canShutdown = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCanShutdown() {
        bitField0_ = (bitField0_ & ~0x00000004);
        canShutdown_ = false;
        onChanged();
        return this;
      }

      private boolean hasWifi_ ;
      /**
       * <pre>
       * Indicates that the device has native wifi capability
       * </pre>
       *
       * <code>bool hasWifi = 4;</code>
       * @return The hasWifi.
       */
      @java.lang.Override
      public boolean getHasWifi() {
        return hasWifi_;
      }
      /**
       * <pre>
       * Indicates that the device has native wifi capability
       * </pre>
       *
       * <code>bool hasWifi = 4;</code>
       * @param value The hasWifi to set.
       * @return This builder for chaining.
       */
      public Builder setHasWifi(boolean value) {
        
        hasWifi_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Indicates that the device has native wifi capability
       * </pre>
       *
       * <code>bool hasWifi = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHasWifi() {
        bitField0_ = (bitField0_ & ~0x00000008);
        hasWifi_ = false;
        onChanged();
        return this;
      }

      private boolean hasBluetooth_ ;
      /**
       * <pre>
       * Indicates that the device has native bluetooth capability
       * </pre>
       *
       * <code>bool hasBluetooth = 5;</code>
       * @return The hasBluetooth.
       */
      @java.lang.Override
      public boolean getHasBluetooth() {
        return hasBluetooth_;
      }
      /**
       * <pre>
       * Indicates that the device has native bluetooth capability
       * </pre>
       *
       * <code>bool hasBluetooth = 5;</code>
       * @param value The hasBluetooth to set.
       * @return This builder for chaining.
       */
      public Builder setHasBluetooth(boolean value) {
        
        hasBluetooth_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Indicates that the device has native bluetooth capability
       * </pre>
       *
       * <code>bool hasBluetooth = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearHasBluetooth() {
        bitField0_ = (bitField0_ & ~0x00000010);
        hasBluetooth_ = false;
        onChanged();
        return this;
      }

      private boolean hasEthernet_ ;
      /**
       * <pre>
       * Indicates that the device has an ethernet peripheral
       * </pre>
       *
       * <code>bool hasEthernet = 6;</code>
       * @return The hasEthernet.
       */
      @java.lang.Override
      public boolean getHasEthernet() {
        return hasEthernet_;
      }
      /**
       * <pre>
       * Indicates that the device has an ethernet peripheral
       * </pre>
       *
       * <code>bool hasEthernet = 6;</code>
       * @param value The hasEthernet to set.
       * @return This builder for chaining.
       */
      public Builder setHasEthernet(boolean value) {
        
        hasEthernet_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Indicates that the device has an ethernet peripheral
       * </pre>
       *
       * <code>bool hasEthernet = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearHasEthernet() {
        bitField0_ = (bitField0_ & ~0x00000020);
        hasEthernet_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DeviceMetadata)
    }

    // @@protoc_insertion_point(class_scope:DeviceMetadata)
    private static final com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata();
    }

    public static com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeviceMetadata>
        PARSER = new com.google.protobuf.AbstractParser<DeviceMetadata>() {
      @java.lang.Override
      public DeviceMetadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DeviceMetadata> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceMetadata> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.geeksville.mesh.DeviceMetadataProtos.DeviceMetadata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeviceMetadata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeviceMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025device_metadata.proto\"\231\001\n\016DeviceMetada" +
      "ta\022\030\n\020firmware_version\030\001 \001(\t\022\034\n\024device_s" +
      "tate_version\030\002 \001(\r\022\023\n\013canShutdown\030\003 \001(\010\022" +
      "\017\n\007hasWifi\030\004 \001(\010\022\024\n\014hasBluetooth\030\005 \001(\010\022\023" +
      "\n\013hasEthernet\030\006 \001(\010Bh\n\023com.geeksville.me" +
      "shB\024DeviceMetadataProtosH\003Z\"github.com/m" +
      "eshtastic/go/generated\252\002\024Meshtastic.Prot" +
      "obufsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DeviceMetadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DeviceMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeviceMetadata_descriptor,
        new java.lang.String[] { "FirmwareVersion", "DeviceStateVersion", "CanShutdown", "HasWifi", "HasBluetooth", "HasEthernet", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
