// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meshmon.proto

package com.geeksville.mesh;

public final class Meshmon {
  private Meshmon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RowOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Row)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 rowid = 1;</code>
     * @return The rowid.
     */
    int getRowid();

    /**
     * <code>fixed32 rx_time = 2;</code>
     * @return The rxTime.
     */
    int getRxTime();

    /**
     * <code>.MeshPacket packet = 3;</code>
     * @return Whether the packet field is set.
     */
    boolean hasPacket();
    /**
     * <code>.MeshPacket packet = 3;</code>
     * @return The packet.
     */
    com.geeksville.mesh.MeshProtos.MeshPacket getPacket();
    /**
     * <code>.MeshPacket packet = 3;</code>
     */
    com.geeksville.mesh.MeshProtos.MeshPacketOrBuilder getPacketOrBuilder();
  }
  /**
   * Protobuf type {@code Row}
   */
  public static final class Row extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Row)
      RowOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Row.newBuilder() to construct.
    private Row(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Row() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Row();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.geeksville.mesh.Meshmon.internal_static_Row_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.geeksville.mesh.Meshmon.internal_static_Row_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.geeksville.mesh.Meshmon.Row.class, com.geeksville.mesh.Meshmon.Row.Builder.class);
    }

    public static final int ROWID_FIELD_NUMBER = 1;
    private int rowid_ = 0;
    /**
     * <code>int32 rowid = 1;</code>
     * @return The rowid.
     */
    @java.lang.Override
    public int getRowid() {
      return rowid_;
    }

    public static final int RX_TIME_FIELD_NUMBER = 2;
    private int rxTime_ = 0;
    /**
     * <code>fixed32 rx_time = 2;</code>
     * @return The rxTime.
     */
    @java.lang.Override
    public int getRxTime() {
      return rxTime_;
    }

    public static final int PACKET_FIELD_NUMBER = 3;
    private com.geeksville.mesh.MeshProtos.MeshPacket packet_;
    /**
     * <code>.MeshPacket packet = 3;</code>
     * @return Whether the packet field is set.
     */
    @java.lang.Override
    public boolean hasPacket() {
      return packet_ != null;
    }
    /**
     * <code>.MeshPacket packet = 3;</code>
     * @return The packet.
     */
    @java.lang.Override
    public com.geeksville.mesh.MeshProtos.MeshPacket getPacket() {
      return packet_ == null ? com.geeksville.mesh.MeshProtos.MeshPacket.getDefaultInstance() : packet_;
    }
    /**
     * <code>.MeshPacket packet = 3;</code>
     */
    @java.lang.Override
    public com.geeksville.mesh.MeshProtos.MeshPacketOrBuilder getPacketOrBuilder() {
      return packet_ == null ? com.geeksville.mesh.MeshProtos.MeshPacket.getDefaultInstance() : packet_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rowid_ != 0) {
        output.writeInt32(1, rowid_);
      }
      if (rxTime_ != 0) {
        output.writeFixed32(2, rxTime_);
      }
      if (packet_ != null) {
        output.writeMessage(3, getPacket());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rowid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rowid_);
      }
      if (rxTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, rxTime_);
      }
      if (packet_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getPacket());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.geeksville.mesh.Meshmon.Row)) {
        return super.equals(obj);
      }
      com.geeksville.mesh.Meshmon.Row other = (com.geeksville.mesh.Meshmon.Row) obj;

      if (getRowid()
          != other.getRowid()) return false;
      if (getRxTime()
          != other.getRxTime()) return false;
      if (hasPacket() != other.hasPacket()) return false;
      if (hasPacket()) {
        if (!getPacket()
            .equals(other.getPacket())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROWID_FIELD_NUMBER;
      hash = (53 * hash) + getRowid();
      hash = (37 * hash) + RX_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getRxTime();
      if (hasPacket()) {
        hash = (37 * hash) + PACKET_FIELD_NUMBER;
        hash = (53 * hash) + getPacket().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.geeksville.mesh.Meshmon.Row parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.geeksville.mesh.Meshmon.Row parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.geeksville.mesh.Meshmon.Row parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.geeksville.mesh.Meshmon.Row parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.geeksville.mesh.Meshmon.Row parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.geeksville.mesh.Meshmon.Row parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.geeksville.mesh.Meshmon.Row parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.geeksville.mesh.Meshmon.Row parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.geeksville.mesh.Meshmon.Row parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.geeksville.mesh.Meshmon.Row parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.geeksville.mesh.Meshmon.Row parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.geeksville.mesh.Meshmon.Row parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.geeksville.mesh.Meshmon.Row prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Row}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Row)
        com.geeksville.mesh.Meshmon.RowOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.geeksville.mesh.Meshmon.internal_static_Row_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.geeksville.mesh.Meshmon.internal_static_Row_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.geeksville.mesh.Meshmon.Row.class, com.geeksville.mesh.Meshmon.Row.Builder.class);
      }

      // Construct using com.geeksville.mesh.Meshmon.Row.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        rowid_ = 0;
        rxTime_ = 0;
        packet_ = null;
        if (packetBuilder_ != null) {
          packetBuilder_.dispose();
          packetBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.geeksville.mesh.Meshmon.internal_static_Row_descriptor;
      }

      @java.lang.Override
      public com.geeksville.mesh.Meshmon.Row getDefaultInstanceForType() {
        return com.geeksville.mesh.Meshmon.Row.getDefaultInstance();
      }

      @java.lang.Override
      public com.geeksville.mesh.Meshmon.Row build() {
        com.geeksville.mesh.Meshmon.Row result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.geeksville.mesh.Meshmon.Row buildPartial() {
        com.geeksville.mesh.Meshmon.Row result = new com.geeksville.mesh.Meshmon.Row(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.geeksville.mesh.Meshmon.Row result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.rowid_ = rowid_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.rxTime_ = rxTime_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.packet_ = packetBuilder_ == null
              ? packet_
              : packetBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.geeksville.mesh.Meshmon.Row) {
          return mergeFrom((com.geeksville.mesh.Meshmon.Row)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.geeksville.mesh.Meshmon.Row other) {
        if (other == com.geeksville.mesh.Meshmon.Row.getDefaultInstance()) return this;
        if (other.getRowid() != 0) {
          setRowid(other.getRowid());
        }
        if (other.getRxTime() != 0) {
          setRxTime(other.getRxTime());
        }
        if (other.hasPacket()) {
          mergePacket(other.getPacket());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                rowid_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 21: {
                rxTime_ = input.readFixed32();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              case 26: {
                input.readMessage(
                    getPacketFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int rowid_ ;
      /**
       * <code>int32 rowid = 1;</code>
       * @return The rowid.
       */
      @java.lang.Override
      public int getRowid() {
        return rowid_;
      }
      /**
       * <code>int32 rowid = 1;</code>
       * @param value The rowid to set.
       * @return This builder for chaining.
       */
      public Builder setRowid(int value) {
        
        rowid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 rowid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRowid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rowid_ = 0;
        onChanged();
        return this;
      }

      private int rxTime_ ;
      /**
       * <code>fixed32 rx_time = 2;</code>
       * @return The rxTime.
       */
      @java.lang.Override
      public int getRxTime() {
        return rxTime_;
      }
      /**
       * <code>fixed32 rx_time = 2;</code>
       * @param value The rxTime to set.
       * @return This builder for chaining.
       */
      public Builder setRxTime(int value) {
        
        rxTime_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>fixed32 rx_time = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRxTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rxTime_ = 0;
        onChanged();
        return this;
      }

      private com.geeksville.mesh.MeshProtos.MeshPacket packet_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.geeksville.mesh.MeshProtos.MeshPacket, com.geeksville.mesh.MeshProtos.MeshPacket.Builder, com.geeksville.mesh.MeshProtos.MeshPacketOrBuilder> packetBuilder_;
      /**
       * <code>.MeshPacket packet = 3;</code>
       * @return Whether the packet field is set.
       */
      public boolean hasPacket() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.MeshPacket packet = 3;</code>
       * @return The packet.
       */
      public com.geeksville.mesh.MeshProtos.MeshPacket getPacket() {
        if (packetBuilder_ == null) {
          return packet_ == null ? com.geeksville.mesh.MeshProtos.MeshPacket.getDefaultInstance() : packet_;
        } else {
          return packetBuilder_.getMessage();
        }
      }
      /**
       * <code>.MeshPacket packet = 3;</code>
       */
      public Builder setPacket(com.geeksville.mesh.MeshProtos.MeshPacket value) {
        if (packetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          packet_ = value;
        } else {
          packetBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.MeshPacket packet = 3;</code>
       */
      public Builder setPacket(
          com.geeksville.mesh.MeshProtos.MeshPacket.Builder builderForValue) {
        if (packetBuilder_ == null) {
          packet_ = builderForValue.build();
        } else {
          packetBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.MeshPacket packet = 3;</code>
       */
      public Builder mergePacket(com.geeksville.mesh.MeshProtos.MeshPacket value) {
        if (packetBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            packet_ != null &&
            packet_ != com.geeksville.mesh.MeshProtos.MeshPacket.getDefaultInstance()) {
            getPacketBuilder().mergeFrom(value);
          } else {
            packet_ = value;
          }
        } else {
          packetBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.MeshPacket packet = 3;</code>
       */
      public Builder clearPacket() {
        bitField0_ = (bitField0_ & ~0x00000004);
        packet_ = null;
        if (packetBuilder_ != null) {
          packetBuilder_.dispose();
          packetBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.MeshPacket packet = 3;</code>
       */
      public com.geeksville.mesh.MeshProtos.MeshPacket.Builder getPacketBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getPacketFieldBuilder().getBuilder();
      }
      /**
       * <code>.MeshPacket packet = 3;</code>
       */
      public com.geeksville.mesh.MeshProtos.MeshPacketOrBuilder getPacketOrBuilder() {
        if (packetBuilder_ != null) {
          return packetBuilder_.getMessageOrBuilder();
        } else {
          return packet_ == null ?
              com.geeksville.mesh.MeshProtos.MeshPacket.getDefaultInstance() : packet_;
        }
      }
      /**
       * <code>.MeshPacket packet = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.geeksville.mesh.MeshProtos.MeshPacket, com.geeksville.mesh.MeshProtos.MeshPacket.Builder, com.geeksville.mesh.MeshProtos.MeshPacketOrBuilder> 
          getPacketFieldBuilder() {
        if (packetBuilder_ == null) {
          packetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.geeksville.mesh.MeshProtos.MeshPacket, com.geeksville.mesh.MeshProtos.MeshPacket.Builder, com.geeksville.mesh.MeshProtos.MeshPacketOrBuilder>(
                  getPacket(),
                  getParentForChildren(),
                  isClean());
          packet_ = null;
        }
        return packetBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Row)
    }

    // @@protoc_insertion_point(class_scope:Row)
    private static final com.geeksville.mesh.Meshmon.Row DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.geeksville.mesh.Meshmon.Row();
    }

    public static com.geeksville.mesh.Meshmon.Row getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Row>
        PARSER = new com.google.protobuf.AbstractParser<Row>() {
      @java.lang.Override
      public Row parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Row> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Row> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.geeksville.mesh.Meshmon.Row getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Row rows = 1;</code>
     */
    java.util.List<com.geeksville.mesh.Meshmon.Row> 
        getRowsList();
    /**
     * <code>repeated .Row rows = 1;</code>
     */
    com.geeksville.mesh.Meshmon.Row getRows(int index);
    /**
     * <code>repeated .Row rows = 1;</code>
     */
    int getRowsCount();
    /**
     * <code>repeated .Row rows = 1;</code>
     */
    java.util.List<? extends com.geeksville.mesh.Meshmon.RowOrBuilder> 
        getRowsOrBuilderList();
    /**
     * <code>repeated .Row rows = 1;</code>
     */
    com.geeksville.mesh.Meshmon.RowOrBuilder getRowsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      rows_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.geeksville.mesh.Meshmon.internal_static_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.geeksville.mesh.Meshmon.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.geeksville.mesh.Meshmon.Response.class, com.geeksville.mesh.Meshmon.Response.Builder.class);
    }

    public static final int ROWS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.geeksville.mesh.Meshmon.Row> rows_;
    /**
     * <code>repeated .Row rows = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.geeksville.mesh.Meshmon.Row> getRowsList() {
      return rows_;
    }
    /**
     * <code>repeated .Row rows = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.geeksville.mesh.Meshmon.RowOrBuilder> 
        getRowsOrBuilderList() {
      return rows_;
    }
    /**
     * <code>repeated .Row rows = 1;</code>
     */
    @java.lang.Override
    public int getRowsCount() {
      return rows_.size();
    }
    /**
     * <code>repeated .Row rows = 1;</code>
     */
    @java.lang.Override
    public com.geeksville.mesh.Meshmon.Row getRows(int index) {
      return rows_.get(index);
    }
    /**
     * <code>repeated .Row rows = 1;</code>
     */
    @java.lang.Override
    public com.geeksville.mesh.Meshmon.RowOrBuilder getRowsOrBuilder(
        int index) {
      return rows_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < rows_.size(); i++) {
        output.writeMessage(1, rows_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < rows_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, rows_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.geeksville.mesh.Meshmon.Response)) {
        return super.equals(obj);
      }
      com.geeksville.mesh.Meshmon.Response other = (com.geeksville.mesh.Meshmon.Response) obj;

      if (!getRowsList()
          .equals(other.getRowsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRowsCount() > 0) {
        hash = (37 * hash) + ROWS_FIELD_NUMBER;
        hash = (53 * hash) + getRowsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.geeksville.mesh.Meshmon.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.geeksville.mesh.Meshmon.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.geeksville.mesh.Meshmon.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.geeksville.mesh.Meshmon.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.geeksville.mesh.Meshmon.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.geeksville.mesh.Meshmon.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.geeksville.mesh.Meshmon.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.geeksville.mesh.Meshmon.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.geeksville.mesh.Meshmon.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.geeksville.mesh.Meshmon.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.geeksville.mesh.Meshmon.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.geeksville.mesh.Meshmon.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.geeksville.mesh.Meshmon.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        com.geeksville.mesh.Meshmon.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.geeksville.mesh.Meshmon.internal_static_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.geeksville.mesh.Meshmon.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.geeksville.mesh.Meshmon.Response.class, com.geeksville.mesh.Meshmon.Response.Builder.class);
      }

      // Construct using com.geeksville.mesh.Meshmon.Response.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
        } else {
          rows_ = null;
          rowsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.geeksville.mesh.Meshmon.internal_static_Response_descriptor;
      }

      @java.lang.Override
      public com.geeksville.mesh.Meshmon.Response getDefaultInstanceForType() {
        return com.geeksville.mesh.Meshmon.Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.geeksville.mesh.Meshmon.Response build() {
        com.geeksville.mesh.Meshmon.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.geeksville.mesh.Meshmon.Response buildPartial() {
        com.geeksville.mesh.Meshmon.Response result = new com.geeksville.mesh.Meshmon.Response(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.geeksville.mesh.Meshmon.Response result) {
        if (rowsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            rows_ = java.util.Collections.unmodifiableList(rows_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.rows_ = rows_;
        } else {
          result.rows_ = rowsBuilder_.build();
        }
      }

      private void buildPartial0(com.geeksville.mesh.Meshmon.Response result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.geeksville.mesh.Meshmon.Response) {
          return mergeFrom((com.geeksville.mesh.Meshmon.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.geeksville.mesh.Meshmon.Response other) {
        if (other == com.geeksville.mesh.Meshmon.Response.getDefaultInstance()) return this;
        if (rowsBuilder_ == null) {
          if (!other.rows_.isEmpty()) {
            if (rows_.isEmpty()) {
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRowsIsMutable();
              rows_.addAll(other.rows_);
            }
            onChanged();
          }
        } else {
          if (!other.rows_.isEmpty()) {
            if (rowsBuilder_.isEmpty()) {
              rowsBuilder_.dispose();
              rowsBuilder_ = null;
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000001);
              rowsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRowsFieldBuilder() : null;
            } else {
              rowsBuilder_.addAllMessages(other.rows_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.geeksville.mesh.Meshmon.Row m =
                    input.readMessage(
                        com.geeksville.mesh.Meshmon.Row.parser(),
                        extensionRegistry);
                if (rowsBuilder_ == null) {
                  ensureRowsIsMutable();
                  rows_.add(m);
                } else {
                  rowsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.geeksville.mesh.Meshmon.Row> rows_ =
        java.util.Collections.emptyList();
      private void ensureRowsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          rows_ = new java.util.ArrayList<com.geeksville.mesh.Meshmon.Row>(rows_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.geeksville.mesh.Meshmon.Row, com.geeksville.mesh.Meshmon.Row.Builder, com.geeksville.mesh.Meshmon.RowOrBuilder> rowsBuilder_;

      /**
       * <code>repeated .Row rows = 1;</code>
       */
      public java.util.List<com.geeksville.mesh.Meshmon.Row> getRowsList() {
        if (rowsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rows_);
        } else {
          return rowsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Row rows = 1;</code>
       */
      public int getRowsCount() {
        if (rowsBuilder_ == null) {
          return rows_.size();
        } else {
          return rowsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Row rows = 1;</code>
       */
      public com.geeksville.mesh.Meshmon.Row getRows(int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);
        } else {
          return rowsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Row rows = 1;</code>
       */
      public Builder setRows(
          int index, com.geeksville.mesh.Meshmon.Row value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.set(index, value);
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Row rows = 1;</code>
       */
      public Builder setRows(
          int index, com.geeksville.mesh.Meshmon.Row.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.set(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Row rows = 1;</code>
       */
      public Builder addRows(com.geeksville.mesh.Meshmon.Row value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Row rows = 1;</code>
       */
      public Builder addRows(
          int index, com.geeksville.mesh.Meshmon.Row value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(index, value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Row rows = 1;</code>
       */
      public Builder addRows(
          com.geeksville.mesh.Meshmon.Row.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Row rows = 1;</code>
       */
      public Builder addRows(
          int index, com.geeksville.mesh.Meshmon.Row.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Row rows = 1;</code>
       */
      public Builder addAllRows(
          java.lang.Iterable<? extends com.geeksville.mesh.Meshmon.Row> values) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rows_);
          onChanged();
        } else {
          rowsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Row rows = 1;</code>
       */
      public Builder clearRows() {
        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          rowsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Row rows = 1;</code>
       */
      public Builder removeRows(int index) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.remove(index);
          onChanged();
        } else {
          rowsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Row rows = 1;</code>
       */
      public com.geeksville.mesh.Meshmon.Row.Builder getRowsBuilder(
          int index) {
        return getRowsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Row rows = 1;</code>
       */
      public com.geeksville.mesh.Meshmon.RowOrBuilder getRowsOrBuilder(
          int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);  } else {
          return rowsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Row rows = 1;</code>
       */
      public java.util.List<? extends com.geeksville.mesh.Meshmon.RowOrBuilder> 
           getRowsOrBuilderList() {
        if (rowsBuilder_ != null) {
          return rowsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rows_);
        }
      }
      /**
       * <code>repeated .Row rows = 1;</code>
       */
      public com.geeksville.mesh.Meshmon.Row.Builder addRowsBuilder() {
        return getRowsFieldBuilder().addBuilder(
            com.geeksville.mesh.Meshmon.Row.getDefaultInstance());
      }
      /**
       * <code>repeated .Row rows = 1;</code>
       */
      public com.geeksville.mesh.Meshmon.Row.Builder addRowsBuilder(
          int index) {
        return getRowsFieldBuilder().addBuilder(
            index, com.geeksville.mesh.Meshmon.Row.getDefaultInstance());
      }
      /**
       * <code>repeated .Row rows = 1;</code>
       */
      public java.util.List<com.geeksville.mesh.Meshmon.Row.Builder> 
           getRowsBuilderList() {
        return getRowsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.geeksville.mesh.Meshmon.Row, com.geeksville.mesh.Meshmon.Row.Builder, com.geeksville.mesh.Meshmon.RowOrBuilder> 
          getRowsFieldBuilder() {
        if (rowsBuilder_ == null) {
          rowsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.geeksville.mesh.Meshmon.Row, com.geeksville.mesh.Meshmon.Row.Builder, com.geeksville.mesh.Meshmon.RowOrBuilder>(
                  rows_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          rows_ = null;
        }
        return rowsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final com.geeksville.mesh.Meshmon.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.geeksville.mesh.Meshmon.Response();
    }

    public static com.geeksville.mesh.Meshmon.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.geeksville.mesh.Meshmon.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Row_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Row_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmeshmon.proto\032\nmesh.proto\"B\n\003Row\022\r\n\005ro" +
      "wid\030\001 \001(\005\022\017\n\007rx_time\030\002 \001(\007\022\033\n\006packet\030\003 \001" +
      "(\0132\013.MeshPacket\"\036\n\010Response\022\022\n\004rows\030\001 \003(" +
      "\0132\004.RowB\027\n\023com.geeksville.meshH\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.geeksville.mesh.MeshProtos.getDescriptor(),
        });
    internal_static_Row_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Row_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Row_descriptor,
        new java.lang.String[] { "Rowid", "RxTime", "Packet", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Rows", });
    com.geeksville.mesh.MeshProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
