name: Main

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: lein deps
    - name: Run linter
      run: lein clj-kondo
    - name: Run tests
      run: lein test
    - name: Build
      run: lein uberjar
    - name: Build Changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v3
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: target/*.jar
        body: ${{steps.github_release.outputs.changelog}}
